name: cd

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  upload-binaries:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    if: github.repository == 'major/fez'
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0  # v6.0.3
        with:
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9  # stable
        with:
          toolchain: "1.92"
          targets: ${{ matrix.target }}
      - name: Build and upload fez binary
        uses: taiki-e/upload-rust-binary-action@57510bf386b3945b57963e73201cea60ca18dff4  # v1.9.1
        with:
          bin: fez
          target: ${{ matrix.target }}
          archive: fez-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
